# Generated by Django 4.2.3 on 2023-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina_virtual_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'comercial'), (3, 'asociado')], default=1),
        ),
    ]
