# Generated by Django 4.2.3 on 2023-07-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina_virtual_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
