# Generated by Django 4.2.3 on 2023-07-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina_virtual_app', '0003_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('numero_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=200)),
                ('lugar_expedicion', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(max_length=200)),
                ('tipo_asociado', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField()),
                ('deuda_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=200)),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina_virtual_app.comercial')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=200)),
                ('valor_semana', models.IntegerField()),
                ('valor_pagado', models.IntegerField()),
                ('saldo_restante', models.IntegerField()),
                ('semana', models.CharField(max_length=200)),
                ('id_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.asociado')),
                ('id_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.comercial')),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='TipoSemana',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_semana', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('asociados', models.IntegerField()),
                ('contratos', models.ManyToManyField(to='oficina_virtual_app.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('rc', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('destino', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('cuota_administrativa', models.IntegerField()),
                ('numero_cuenta', models.CharField(max_length=200)),
                ('tipo_pago', models.CharField(max_length=200)),
                ('pagos_id', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_rel', to='oficina_virtual_app.asociado')),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.tiposemana'),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('valor_efectivo', models.IntegerField()),
                ('valor_tokens', models.IntegerField()),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.comercial')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='asociado',
            name='contratos',
            field=models.ManyToManyField(to='oficina_virtual_app.contrato'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='pagos',
            field=models.ManyToManyField(related_name='asociados_rel', to='oficina_virtual_app.pago'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='tipo_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina_virtual_app.tiposemana'),
        ),
    ]
